"""empty message

Revision ID: 0e8df381d191
Revises: f0e081366855
Create Date: 2019-05-17 11:15:15.542269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8df381d191'
down_revision = 'f0e081366855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'containers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.drop_column('containers', 'user_id')
    # ### end Alembic commands ###
