"""empty message

Revision ID: 923ea168a112
Revises: faa1fffdff75
Create Date: 2019-06-06 07:50:36.318262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923ea168a112'
down_revision = 'faa1fffdff75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_create_time'), 'users', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_create_time'), table_name='users')
    op.drop_column('users', 'create_time')
    # ### end Alembic commands ###
