"""empty message

Revision ID: 9c5f23700eb9
Revises: 0e8df381d191
Create Date: 2019-05-17 11:33:35.057138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c5f23700eb9'
down_revision = '0e8df381d191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('username', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
