"""empty message

Revision ID: bd0293be9433
Revises: 94af736d4447
Create Date: 2019-05-06 12:30:02.208426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0293be9433'
down_revision = '94af736d4447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('container_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'container_name')
    # ### end Alembic commands ###
