"""empty message

Revision ID: f0e081366855
Revises: bd0293be9433
Create Date: 2019-05-09 23:33:06.784643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e081366855'
down_revision = 'bd0293be9433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('username', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'username')
    # ### end Alembic commands ###
